Implement webhook verification
fulfilio/fulfil-python-api pull request #64
Opened 2019-07-20 14:33 UTC by sharoonthomas

2019-07-22 10:04 UTC, prakashpp requested changes

2019-07-22 10:04 UTC, prakashpp commented on README.rst
> +         secret,     # This should be saved somewhere
should there be documentation on how to obtain this secret from fulfil?

2019-07-22 10:05 UTC, prakashpp approved these changes

2019-07-23 07:54 UTC, Anmol-Gulati approved these changes

2019-07-23 12:10 UTC, tarunbhardwaj approved these changes

2019-07-23 12:10 UTC, merged